### PR TITLE
HWC will open virtio_gpu for display

### PR DESCRIPTION
**Pull request by kanlihu**
HWC will check every node and open properly display card.
dgpu passthrough     display with dGPU
igpu_sriov           display with virtio_gpu
igpu_sriov + dgpu_passthrough    display with virtio_gpu

Tracked-On: OAM-122478

### CODE REVIEW

**Review by feijiang1 — APPROVED** [review]
LGTM

**Review by feijiang1 — APPROVED** [review]
LGTM

**Comment by YuanjunHuang** [comment]
Commit message is too simple and kind of confusing. Please explain more detail.

**Review by feijiang1 — APPROVED** [review]
LGTM

**Review by YuanjunHuang — APPROVED** [review]

**Review by phreer — APPROVED** [review]
LGTM, dGPU VF works with this PR.

**Pull request merged**
